#!/usr/bin/env bash
# Bash script that transfers a file from our client to a server
# Accepts four parameters:
# The path to the file to be transferred
# The IP of the server we want to transfer the file to
# The username scp connects with
# The path to the SSH private key that scp uses

error_msg="Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"


if [ $# -lt 3 ]; then
    echo "$error_msg"
    exit 1
fi

# assigning the commanline argument to a variable
file_path=$1
IP=$2
user=$3
SSH_key=$4

if scp -o StrictHostKeyChecking=no -i "$SSH_key" "$file_path" "$user@$IP:~/"; then
    echo "FILE TRANSFER SUCCESSFUL!"
else
    echo "FILE TRANSFER FAILED!"
fi
