#!/usr/bin/env bash
# Installs nginx web server that listens to port 80
#
sudo apt update
sudo apt-get -y install nginx
sudo fw allow 'Nginx HTTP'
sudo sh -c 'echo "Hello World!" > /var/www/html/index.html'
sudo nginx -s reload