#!/usr/bin/env bash
# this script configures Nginx server so that /redirect_me is redirecting to another page.
# the redirection uses
# “301 Moved Permanently”

sudo apt-get update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
echo "Hello World!" > /var/www/html/index.html

# configuring a new default server block
sudo sh -c "echo 'server {
        listen 80 default_server;
        listen [::]:80 default_server;

	location /redirect_me {
            return 301 https://www.youtube.com;
        }

        root /var/www/html;
        index index.html index.htm index.nginx-debian.html;

        server_name _;

        location / {
                try_files \$uri \$uri/ =404;
        }
}' > /etc/nginx/sites-available/default"
sudo service nginx restart
