#!/usr/bin/env bash
# this script installs and configures nginx web server, adds a custom Nginx response header

sudo apt-get update &>/dev/null
# checking if nginx exist already
if ! command -v nginx; then
	# installing nginx
	echo "Installing Nginx..."
	sudo apt-get -y install nginx &>/dev/null
	sudo ufw allow 'Nginx HTTP' &>/dev/null
fi

# configuring nginx to add a custom header
sudo sh -c 'echo "server {
        listen 80 default_server;
        listen [::]:80 default_server;
	
	add_header X-Served-By \$hostname;

        root /var/www/html;
        index index.html index.htm index.nginx-debian.html;
	
        server_name _;

        location / {
                try_files \$uri \$uri/ =404;
        }
}" > /etc/nginx/sites-available/default'

sudo nginx -t
sudo service nginx restart
