#!/usr/bin/env bash
# Using your debugging skills, find out what’s keeping your Ubuntu container’s
# Nginx installation from listening on port 80. Feel free to install whatever tool
# you need, start and destroy as many containers as you need to debug the issue.
# Then, write a Bash script with the minimum number of commands to automate your fix.

#kill exist nginx process
pkill -o nginx

# removing the buggy file
rm /etc/nginx/sites-enabled/default

# create a line to the default file
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled

# restarting nginx
service nginx restart