#!/usr/bin/env bash
# Creates the file /var/run/myscript.pid containing its PID
# Displays To infinity and beyond indefinitely
# Displays I hate the kill command when receiving a SIGTERM signal
# Displays Y U no love me?! when receiving a SIGINT signal
# Deletes the file /var/run/myscript.pid and terminates itse
FILE="/var/run/myscript.pid"

rm_n_exit()
{
  rm -f $FILE;
  exit
}
echo $$ >> $FILE
while true; do
  echo "To infinity and beyond"
  sleep 2
done

trap "echo 'I hate the kill command' && rm_n_exit" SIGTERM
trap "echo 'Y U no love me?!'" SIGINT
trap "echo 'I hate the kill command' && rm_n_exit" SIGQUIT
