#!/usr/bin/env bash

FILE="/var/run/myscript.pid"

rm_n_exit()
{
  rm -f $FILE;
  exit
}

while true; do
  echo "To infinity and beyond"
  sleep 2
done

trap "echo 'I hate the kill command' && rm_n_exit" SIGTERM
trap "echo 'Y U no love me?!'" SIGINT
trap "rm_n_exit" SIGQUIT
