#!/usr/bin/env bash

#  a Bash script that configures an Ubuntu server with the below requirements:

# localhost resolves to 127.0.0.2
# facebook.com resolves to 8.8.8.8.

cp /etc/hosts dup_hosts
sed -i 's/127.0.0.1/127.0.0.2/' dup_hosts
sed -i '2i8.8.8.8 facebook.com' dup_hosts
cp -f dup_hosts /etc/hosts
