#!/bin/usr/env bash
# this script installs Apache and ensure that when you query the root
# it returns a page containing 'Hello Holberton'

sudo apt update
sudo apt install -y apache2
echo "Hello Holberton" | sudo tee /var/www/html/index.html
